# Use a imagem base do Node.js 16
FROM node:16

# Definir o fuso horário sem interação do usuário
ENV TZ=America/Sao_Paulo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Definir o diretório de trabalho
WORKDIR /app

# Copiar package.json e package-lock.json (se existir) para instalar dependências
COPY package*.json ./

# Instalar dependências
RUN npm install

# Copiar o restante dos arquivos
COPY . .

# Expor a porta
EXPOSE 3000

# Comando para iniciar o servidor de desenvolvimento
CMD ["npm", "run", "dev"]
