
interface _GlobalComponents {
      'AuthTitle': typeof import("../components/auth/Title.vue")['default']
    'GlobalBanner': typeof import("../components/global/Banner.vue")['default']
    'GlobalLoadingDefault': typeof import("../components/global/LoadingDefault.vue")['default']
    'GlobalLoadingProject': typeof import("../components/global/LoadingProject.vue")['default']
    'GlobalTitleRegister': typeof import("../components/global/TitleRegister.vue")['default']
    'GlobalTotalModules': typeof import("../components/global/TotalModules")['default']
    'HomeCarousel': typeof import("../components/home/Carousel.vue")['default']
    'HomeKwpGraphic': typeof import("../components/home/KwpGraphic.vue")['default']
    'HomeLastUpdates': typeof import("../components/home/LastUpdates.vue")['default']
    'LayoutFooter': typeof import("../components/layout/Footer.vue")['default']
    'LayoutLateralMenu': typeof import("../components/layout/LateralMenu.vue")['default']
    'LayoutLoading': typeof import("../components/layout/Loading.vue")['default']
    'ProjectAreaDesignerUpdate': typeof import("../components/project-area/DesignerUpdate.vue")['default']
    'ProjectAreaFileAttachment': typeof import("../components/project-area/FileAttachment.vue")['default']
    'ProjectAreaProjectDetails': typeof import("../components/project-area/ProjectDetails.vue")['default']
    'ProjectAreaProjectProgress': typeof import("../components/project-area/ProjectProgress.vue")['default']
    'ProjectAreaProjectRegisterFileList': typeof import("../components/project-area/ProjectRegisterFileList.vue")['default']
    'ProjectAreaRequestInspection': typeof import("../components/project-area/RequestInspection.vue")['default']
    'ProjectCommissioningPhotovoltaicInversor': typeof import("../components/project-commissioning/photovoltaic/Inversor.vue")['default']
    'ProjectCommissioningPhotovoltaicKitData': typeof import("../components/project-commissioning/photovoltaic/KitData.vue")['default']
    'ProjectCommissioningPhotovoltaicModule': typeof import("../components/project-commissioning/photovoltaic/Module.vue")['default']
    'ProjectPosInstallationRoofData': typeof import("../components/project-pos-installation/RoofData.vue")['default']
    'ProjectPreInstallationDefaultEntry': typeof import("../components/project-pre-installation/DefaultEntry.vue")['default']
    'ProjectPreInstallationRoofData': typeof import("../components/project-pre-installation/RoofData.vue")['default']
    'ProjectRegistrationAnnexList': typeof import("../components/project-registration/AnnexList.vue")['default']
    'ProjectRegistrationGeneralData': typeof import("../components/project-registration/GeneralData.vue")['default']
    'ProjectRegistrationImportantDocs': typeof import("../components/project-registration/ImportantDocs.vue")['default']
    'ProjectRegistrationPhotovoltaicInversor': typeof import("../components/project-registration/photovoltaic/Inversor.vue")['default']
    'ProjectRegistrationPhotovoltaicKitData': typeof import("../components/project-registration/photovoltaic/KitData.vue")['default']
    'ProjectRegistrationPhotovoltaicModule': typeof import("../components/project-registration/photovoltaic/Module.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
      'LazyAuthTitle': typeof import("../components/auth/Title.vue")['default']
    'LazyGlobalBanner': typeof import("../components/global/Banner.vue")['default']
    'LazyGlobalLoadingDefault': typeof import("../components/global/LoadingDefault.vue")['default']
    'LazyGlobalLoadingProject': typeof import("../components/global/LoadingProject.vue")['default']
    'LazyGlobalTitleRegister': typeof import("../components/global/TitleRegister.vue")['default']
    'LazyGlobalTotalModules': typeof import("../components/global/TotalModules")['default']
    'LazyHomeCarousel': typeof import("../components/home/Carousel.vue")['default']
    'LazyHomeKwpGraphic': typeof import("../components/home/KwpGraphic.vue")['default']
    'LazyHomeLastUpdates': typeof import("../components/home/LastUpdates.vue")['default']
    'LazyLayoutFooter': typeof import("../components/layout/Footer.vue")['default']
    'LazyLayoutLateralMenu': typeof import("../components/layout/LateralMenu.vue")['default']
    'LazyLayoutLoading': typeof import("../components/layout/Loading.vue")['default']
    'LazyProjectAreaDesignerUpdate': typeof import("../components/project-area/DesignerUpdate.vue")['default']
    'LazyProjectAreaFileAttachment': typeof import("../components/project-area/FileAttachment.vue")['default']
    'LazyProjectAreaProjectDetails': typeof import("../components/project-area/ProjectDetails.vue")['default']
    'LazyProjectAreaProjectProgress': typeof import("../components/project-area/ProjectProgress.vue")['default']
    'LazyProjectAreaProjectRegisterFileList': typeof import("../components/project-area/ProjectRegisterFileList.vue")['default']
    'LazyProjectAreaRequestInspection': typeof import("../components/project-area/RequestInspection.vue")['default']
    'LazyProjectCommissioningPhotovoltaicInversor': typeof import("../components/project-commissioning/photovoltaic/Inversor.vue")['default']
    'LazyProjectCommissioningPhotovoltaicKitData': typeof import("../components/project-commissioning/photovoltaic/KitData.vue")['default']
    'LazyProjectCommissioningPhotovoltaicModule': typeof import("../components/project-commissioning/photovoltaic/Module.vue")['default']
    'LazyProjectPosInstallationRoofData': typeof import("../components/project-pos-installation/RoofData.vue")['default']
    'LazyProjectPreInstallationDefaultEntry': typeof import("../components/project-pre-installation/DefaultEntry.vue")['default']
    'LazyProjectPreInstallationRoofData': typeof import("../components/project-pre-installation/RoofData.vue")['default']
    'LazyProjectRegistrationAnnexList': typeof import("../components/project-registration/AnnexList.vue")['default']
    'LazyProjectRegistrationGeneralData': typeof import("../components/project-registration/GeneralData.vue")['default']
    'LazyProjectRegistrationImportantDocs': typeof import("../components/project-registration/ImportantDocs.vue")['default']
    'LazyProjectRegistrationPhotovoltaicInversor': typeof import("../components/project-registration/photovoltaic/Inversor.vue")['default']
    'LazyProjectRegistrationPhotovoltaicKitData': typeof import("../components/project-registration/photovoltaic/KitData.vue")['default']
    'LazyProjectRegistrationPhotovoltaicModule': typeof import("../components/project-registration/photovoltaic/Module.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const AuthTitle: typeof import("../components/auth/Title.vue")['default']
export const GlobalBanner: typeof import("../components/global/Banner.vue")['default']
export const GlobalLoadingDefault: typeof import("../components/global/LoadingDefault.vue")['default']
export const GlobalLoadingProject: typeof import("../components/global/LoadingProject.vue")['default']
export const GlobalTitleRegister: typeof import("../components/global/TitleRegister.vue")['default']
export const GlobalTotalModules: typeof import("../components/global/TotalModules")['default']
export const HomeCarousel: typeof import("../components/home/Carousel.vue")['default']
export const HomeKwpGraphic: typeof import("../components/home/KwpGraphic.vue")['default']
export const HomeLastUpdates: typeof import("../components/home/LastUpdates.vue")['default']
export const LayoutFooter: typeof import("../components/layout/Footer.vue")['default']
export const LayoutLateralMenu: typeof import("../components/layout/LateralMenu.vue")['default']
export const LayoutLoading: typeof import("../components/layout/Loading.vue")['default']
export const ProjectAreaDesignerUpdate: typeof import("../components/project-area/DesignerUpdate.vue")['default']
export const ProjectAreaFileAttachment: typeof import("../components/project-area/FileAttachment.vue")['default']
export const ProjectAreaProjectDetails: typeof import("../components/project-area/ProjectDetails.vue")['default']
export const ProjectAreaProjectProgress: typeof import("../components/project-area/ProjectProgress.vue")['default']
export const ProjectAreaProjectRegisterFileList: typeof import("../components/project-area/ProjectRegisterFileList.vue")['default']
export const ProjectAreaRequestInspection: typeof import("../components/project-area/RequestInspection.vue")['default']
export const ProjectCommissioningPhotovoltaicInversor: typeof import("../components/project-commissioning/photovoltaic/Inversor.vue")['default']
export const ProjectCommissioningPhotovoltaicKitData: typeof import("../components/project-commissioning/photovoltaic/KitData.vue")['default']
export const ProjectCommissioningPhotovoltaicModule: typeof import("../components/project-commissioning/photovoltaic/Module.vue")['default']
export const ProjectPosInstallationRoofData: typeof import("../components/project-pos-installation/RoofData.vue")['default']
export const ProjectPreInstallationDefaultEntry: typeof import("../components/project-pre-installation/DefaultEntry.vue")['default']
export const ProjectPreInstallationRoofData: typeof import("../components/project-pre-installation/RoofData.vue")['default']
export const ProjectRegistrationAnnexList: typeof import("../components/project-registration/AnnexList.vue")['default']
export const ProjectRegistrationGeneralData: typeof import("../components/project-registration/GeneralData.vue")['default']
export const ProjectRegistrationImportantDocs: typeof import("../components/project-registration/ImportantDocs.vue")['default']
export const ProjectRegistrationPhotovoltaicInversor: typeof import("../components/project-registration/photovoltaic/Inversor.vue")['default']
export const ProjectRegistrationPhotovoltaicKitData: typeof import("../components/project-registration/photovoltaic/KitData.vue")['default']
export const ProjectRegistrationPhotovoltaicModule: typeof import("../components/project-registration/photovoltaic/Module.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyAuthTitle: typeof import("../components/auth/Title.vue")['default']
export const LazyGlobalBanner: typeof import("../components/global/Banner.vue")['default']
export const LazyGlobalLoadingDefault: typeof import("../components/global/LoadingDefault.vue")['default']
export const LazyGlobalLoadingProject: typeof import("../components/global/LoadingProject.vue")['default']
export const LazyGlobalTitleRegister: typeof import("../components/global/TitleRegister.vue")['default']
export const LazyGlobalTotalModules: typeof import("../components/global/TotalModules")['default']
export const LazyHomeCarousel: typeof import("../components/home/Carousel.vue")['default']
export const LazyHomeKwpGraphic: typeof import("../components/home/KwpGraphic.vue")['default']
export const LazyHomeLastUpdates: typeof import("../components/home/LastUpdates.vue")['default']
export const LazyLayoutFooter: typeof import("../components/layout/Footer.vue")['default']
export const LazyLayoutLateralMenu: typeof import("../components/layout/LateralMenu.vue")['default']
export const LazyLayoutLoading: typeof import("../components/layout/Loading.vue")['default']
export const LazyProjectAreaDesignerUpdate: typeof import("../components/project-area/DesignerUpdate.vue")['default']
export const LazyProjectAreaFileAttachment: typeof import("../components/project-area/FileAttachment.vue")['default']
export const LazyProjectAreaProjectDetails: typeof import("../components/project-area/ProjectDetails.vue")['default']
export const LazyProjectAreaProjectProgress: typeof import("../components/project-area/ProjectProgress.vue")['default']
export const LazyProjectAreaProjectRegisterFileList: typeof import("../components/project-area/ProjectRegisterFileList.vue")['default']
export const LazyProjectAreaRequestInspection: typeof import("../components/project-area/RequestInspection.vue")['default']
export const LazyProjectCommissioningPhotovoltaicInversor: typeof import("../components/project-commissioning/photovoltaic/Inversor.vue")['default']
export const LazyProjectCommissioningPhotovoltaicKitData: typeof import("../components/project-commissioning/photovoltaic/KitData.vue")['default']
export const LazyProjectCommissioningPhotovoltaicModule: typeof import("../components/project-commissioning/photovoltaic/Module.vue")['default']
export const LazyProjectPosInstallationRoofData: typeof import("../components/project-pos-installation/RoofData.vue")['default']
export const LazyProjectPreInstallationDefaultEntry: typeof import("../components/project-pre-installation/DefaultEntry.vue")['default']
export const LazyProjectPreInstallationRoofData: typeof import("../components/project-pre-installation/RoofData.vue")['default']
export const LazyProjectRegistrationAnnexList: typeof import("../components/project-registration/AnnexList.vue")['default']
export const LazyProjectRegistrationGeneralData: typeof import("../components/project-registration/GeneralData.vue")['default']
export const LazyProjectRegistrationImportantDocs: typeof import("../components/project-registration/ImportantDocs.vue")['default']
export const LazyProjectRegistrationPhotovoltaicInversor: typeof import("../components/project-registration/photovoltaic/Inversor.vue")['default']
export const LazyProjectRegistrationPhotovoltaicKitData: typeof import("../components/project-registration/photovoltaic/KitData.vue")['default']
export const LazyProjectRegistrationPhotovoltaicModule: typeof import("../components/project-registration/photovoltaic/Module.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']

export const componentNames: string[]
